Hệ thống gợi ý là gì & Tại sao cần nó?

    Hệ thống gợi ý là hệ thống học máy dự đoán sở thích người dùng và đề xuất các mục (sản phẩm, nội dung) phù hợp.
        10 triệu cuốn sách (Quá tải thông tin / Information Overload)
        -> Bộ lọc thông minh (AI)
        -> Vài cuốn sách bạn thực sự thích

        => Lọc bỏ nhiễu
        => Cá nhân hóa trải nghiệm
        => Tiết kiệm thời gian tìm kiếm

    Ứng dụng thực tế hàng ngày
        Netflix: Gợi ý phim/series dựa trên lịch sử xem.
        Spotify: Playlist "Discover Weekly" cá nhân hóa.
        Amazon: Mục "Khách hàng mua sản phẩm này cũng mua ... "
        YouTube: Video tiếp theo bạn nên xem (Next Up).
        TikTok: Nội dung trên trang "For You".
        Kết luận: Hệ thống gợi ý hiện diện ở mọi nền tảng số lớn.

Quy trình & Thu thập dữ liệu
    Thu thập dữ liệu -> Xử lý dữ liệu -> Xây dựng mô hình -> Đánh giá/Triển khai

    Phân loại dữ liệu đầu vào
        Dữ liệu Tường minh (Explicit)
            · Mô tả: Người dùng chủ động đánh giá.
            · Ví dụ: Rate 5 sao, like/dislike.
            · Đặc điểm: Chính xác nhưng Ít (User lười đánh giá).

        Dữ liệu Ngầm định (Implicit)
            · Mô tả: Suy luận từ hành vi.
            · Ví dụ: Lịch sử xem, click, thời gian đọc.
            · Đặc điểm: Nhiều nhưng Nhiễu (Xem # Thích).

    Ma trận Người dùng - Mục (User-Item Matrix)
                Movie A     Movie B     Movie C     Movie D

        User 1      5

        User 2                  3

        User 3                              4

        User 4

        User 5

        => Tính thưa (Sparsity): vấn đề thực tế hơn 99% ô là trống vì người dùng chỉ tương tác với một phần nhỏ tổng số mục.
        => Nhiệm vụ của hệ thống: Điền vào các ô '?' (dự đoán điểm số) dựa trên dữ liệu hiện có.

    Xử lý dữ liệu: Chuẩn hóa (Normalization)
        Vấn đề: Bias Thang đo 
            · User A (Dễ tính): Thích = 5, Ghet = 4
            · User B (Khó tính): Thích = 3, Ghet = 1
        => Hậu quả: Điểm số thô không phản ánh đúng mức độ yêu thích nếu so sánh ngang hàng.

    Giải pháp: Mean Centering
        r'ui = rui - ru
        rui: Điểm gốc
        ru: Điểm trung bình của user

        Đưa về cùng một mặt bằng so sánh (dương là thích, âm là không thích so với trung bình của chính họ).



Đánh giá sai số dự đoán

    MAE (Mean Absolute Error): Trung bình khoảng cách tuyệt đối giữa giá trị thực và dự đoán.
        MAE = 1/n x |∑(yi - ŷi)|

    RMSE (Root Mean Square Error): Phạt nặng các sai số lớn do phép bình phương.
        RMSE = √1/n x ∑(n; i=1)(yi​−ŷi)^2

Đánh giá danh sách Top-K: Precision & Recall
    Dùng khi hệ thống đề xuất một danh sách (ví dụ: 5 phim) thay vì dự đoán điểm số cụ thể.

    Công thức:
        Precision@K = Số mục liên quan trong top K / K
            Ví dụ:
                Gợi ý: [A, B, C, D, E]
                -> User thực sự thích: [A, C, F, G]
                -> Kết quả trùng (Relevant): 2 phim (A, C)
                -> Precision@5 = 2 / 5=40%        

        Recall@K = Số mục liên quan trong top K /  (Tổng số mục liên quan)        


Ba phương pháp tiếp cận chính
    Lọc cộng tác (Collaborative Filtering - CF)
        Ý tưởng: Người có sở thích giống nhau trong quá khứ sẽ giống nhau trong tương lai -> Hành vi đám đông.
        Triết lý: Không quan tâm nội dung mục, chỉ quan tâm tương tác cộng đồng.

        User-based CF: Tìm người giống bạn. (Users similar to User U)

        Item-based CF: Tìm mục giống mục bạn thích. (Items similar to Item l)




    
    Lọc dựa trên nội dung (Content-based Filtering)
        Ý tưởng: Gợi ý các mục có đặc điểm tương tự mục người dùng đã thích -> Thuộc tính sản phẩm

    Phương pháp lai (Hybrid)
        Ý tưởng: Kết hợp cả hai để tận dụng ưu điểm và giảm thiểu nhược điểm -> Example: Netflix.

In [79]:
import pandas as pd
import numpy as np

bookDf = pd.read_csv('Books.csv')
ratingDf = pd.read_csv('Ratings.csv')
userDf = pd.read_csv('Users.csv')
ratingDf

C:\Users\Ryan\AppData\Local\Temp\ipykernel_6904\188806887.py:4: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  bookDf = pd.read_csv('Books.csv')

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [63]:
# Count how many times a book is rated
ratingCountDf = ratingDf.groupby('ISBN').count()
print(type(ratingCountDf)) # Data frame
ratingCountDf

ratingCountDf = ratingCountDf['Book-Rating']
print(type(ratingCountDf)) # Series
ratingCountDf

ratingCountDf = ratingCountDf.reset_index(name='User-Rating-Count')
print(type(ratingCountDf)) # DataFrame
print(len(ratingCountDf))
ratingCountDf

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
340556

               ISBN  User-Rating-Count
0        0330299891                  2
1        0375404120                  2
2        0586045007                  1
3        9022906116                  2
4        9032803328                  1
...             ...                ...
340551     cn113107                  1
340552   ooo7156103                  1
340553   §423350229                  1
340554  ´3499128624                  1
340555    Ô½crosoft                  1

[340556 rows x 2 columns]

In [ ]:
# Calculate the mean rating score for each book
ratingMeanDf = ratingDf.groupby('ISBN')['Book-Rating'].mean()
print(type(ratingMeanDf)) # Series
ratingMeanDf = ratingMeanDf.reset_index()
print(type(ratingMeanDf)) # DataFrame
print(len(ratingMeanDf))
ratingMeanDf

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>
340556

               ISBN  Book-Rating
0        0330299891          3.0
1        0375404120          1.5
2        0586045007          0.0
3        9022906116          3.5
4        9032803328          0.0
...             ...          ...
340551     cn113107          0.0
340552   ooo7156103          7.0
340553   §423350229          0.0
340554  ´3499128624          8.0
340555    Ô½crosoft          7.0

[340556 rows x 2 columns]

In [46]:
# Merge ratingCountDf and ratingMeanDf
ratingAggregateDf = ratingCountDf.merge(ratingMeanDf, on='ISBN')
ratingAggregateDf
ratingCountDf

               ISBN  Book-Rating
0        0330299891            2
1        0375404120            2
2        0586045007            1
3        9022906116            2
4        9032803328            1
...             ...          ...
340551     cn113107            1
340552   ooo7156103            1
340553   §423350229            1
340554  ´3499128624            1
340555    Ô½crosoft            1

[340556 rows x 2 columns]

In [82]:
# Merge ratingBookAggregate with bookDf to get more information for a book.
ratingBookAggregateDf = ratingAggregateDf.merge(bookDf, on='ISBN')
print(type(ratingBookAggregateDf)) # dataframe
print(len(ratingBookAggregateDf))
ratingBookAggregateDf.rename(columns={'Book-Rating_x': 'Rating-Count', 'Book-Rating_y': 'Rating-Avg'}, inplace=True)
ratingBookAggregateDf = ratingBookAggregateDf.drop(columns=['Image-URL-M', 'Image-URL-L'])
ratingBookAggregateDf.head()

# Filter to get all the books which has Rating-Count >= 100
popularRatingBookAggregateDf = ratingBookAggregateDf[ratingBookAggregateDf['Rating-Count'] >= 100].reset_index()
print(type(popularRatingBookAggregateDf))
print(len(popularRatingBookAggregateDf))
popularRatingBookAggregateDf.head()

<class 'pandas.core.frame.DataFrame'>
270151
<class 'pandas.core.frame.DataFrame'>
727

,index,ISBN,Rating-Count,Rating-Avg,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S
0,1759,002542730X,171,3.514620,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,3219,0060008032,104,2.442308,Angels,Marian Keyes,2003,HarperTorch,http://images.amazon.com/images/P/0060008032.0...
2,3484,0060096195,107,4.028037,The Boy Next Door,Meggin Cabot,2002,Avon Trade,http://images.amazon.com/images/P/0060096195.0...
3,3989,006016848X,147,2.693878,"Men Are from Mars, Women Are from Venus: A Pra...",John Gray,1992,HarperCollins Publishers,http://images.amazon.com/images/P/006016848X.0...
4,4122,0060173289,130,3.453846,Divine Secrets of the Ya-Ya Sisterhood : A Novel,Rebecca Wells,1996,HarperCollins,http://images.amazon.com/images/P/0060173289.0...

In [86]:
# Count the rating times of each user
activeUser = ratingDf.groupby('User-ID').size().reset_index(name='User-Rating-Count')
print(type(activeUser)) # DataFrame
activeUser

# Filter to get the users who have rating times >= 100
activeUser = activeUser[activeUser['User-Rating-Count'] >= 100].sort_values(by='User-Rating-Count', ascending=False)
print(type(activeUser))
print(len(activeUser))
activeUser


# Active rating by user
activeUserRatingDf = ratingDf[ratingDf['User-ID'].isin(activeUser['User-ID'])]
print(len(activeUserRatingDf))
print(type(activeUserRatingDf))
activeUserRatingDf

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
1847
658805
<class 'pandas.core.frame.DataFrame'>

         User-ID        ISBN  Book-Rating
412       276925  0006511929            0
413       276925  002542730X           10
414       276925  0060520507            0
415       276925  0060930934            0
416       276925  0060951303            0
...          ...         ...          ...
1149633   276680  1884910033            0
1149634   276680  1888173408            7
1149635   276680  1888173564            8
1149636   276680  1888173572            0
1149637   276680  1931561648            9

[658805 rows x 3 columns]

In [92]:
# the books which has popular rating by active users
polularUserBookRatingDf = activeUserRatingDf[activeUserRatingDf['ISBN'].isin(popularRatingBookAggregateDf['ISBN'])]
print(len(polularUserBookRatingDf)) # 65523
polularUserBookRatingDf

# Merge with bookDf to get more book information
polularUserBookRatingDf = polularUserBookRatingDf.merge(bookDf, on='ISBN')
print(len(polularUserBookRatingDf)) # 65523
polularUserBookRatingDf = polularUserBookRatingDf.drop(columns=['Image-URL-M', 'Image-URL-L'])
polularUserBookRatingDf

65523
65523

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S
0,276925,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,276925,0316666343,0,The Lovely Bones: A Novel,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...
2,276925,0385504209,8,The Da Vinci Code,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...
3,276925,0804106304,0,The Joy Luck Club,Amy Tan,1994,Prentice Hall (K-12),http://images.amazon.com/images/P/0804106304.0...
4,276925,0971880107,0,Wild Animus,Rich Shapero,2004,Too Far,http://images.amazon.com/images/P/0971880107.0...
...,...,...,...,...,...,...,...,...
65518,276680,0440221595,8,The Glass Lake,Maeve Binchy,1996,Dell,http://images.amazon.com/images/P/0440221595.0...
65519,276680,0446670251,0,The Virgin Suicides,Jeffrey Eugenides,1994,Warner Books,http://images.amazon.com/images/P/0446670251.0...
65520,276680,0452283205,7,Falling Angels,Tracy Chevalier,2002,Plume Books,http://images.amazon.com/images/P/0452283205.0...
65521,276680,0679731725,0,The Remains of the Day (Vintage International),Kazuo Ishiguro,1993,Vintage Books USA,http://images.amazon.com/images/P/0679731725.0...
65522,276680,0743203631,7,Gap Creek: The Story Of A Marriage,Robert Morgan,2000,Touchstone,http://images.amazon.com/images/P/0743203631.0...

In [93]:
pivot_table = polularUserBookRatingDf.pivot_table(index='Book-Title', columns='User-ID', values='Book-Rating')
pivot_table.head()

pivot_table.fillna(0, inplace=True)
pivot_table.head()

User-ID,254,507,882,1424,1435,1733,1903,2033,2110,2276,...,276018,276463,276680,276925,277427,277478,277639,278137,278188,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Beautiful Mind: The Life of Mathematical Genius and Nobel Laureate John Nash,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
item_similarity = cosine_similarity(pivot_table)
item_similarity.shape

print(item_similarity[:4])

book = 'Harry Potter and the Chamber of Secrets (Book 2)'
book_index = pivot_table.index.tolist().index(book)
print(f'Index of the book "{book}":', book_index)

book_similarities = item_similarity[book_index]
print(book_similarities)

# Top 5 similar books
sorted_indexes = sorted(range(len(book_similarities)), key=lambda k: book_similarities[k], reverse=True)
for i in sorted_indexes[1:6]:
    print(f'Index: {i}, Similarity Score: {book_similarities[i]:.4f}, Book Title: {pivot_table.index[i]}')

[[1.         0.05891323 0.         ... 0.         0.07039485 0.        ]
 [0.05891323 1.         0.24207864 ... 0.12679146 0.04413729 0.16688272]
 [0.         0.24207864 1.         ... 0.11199938 0.02440714 0.05509168]
 [0.         0.         0.         ... 0.05143611 0.         0.        ]]
Index of the book "Harry Potter and the Chamber of Secrets (Book 2)": 216
[0.04229094 0.05161445 0.06726978 0.         0.         0.01992399
 0.01646777 0.09843386 0.         0.06665909 0.09574041 0.
 0.02685106 0.0543404  0.0514492  0.02203904 0.02040047 0.04444827
 0.09702149 0.06093805 0.09132612 0.08353835 0.05096309 0.13789726
 0.         0.10364696 0.08716438 0.01528515 0.10505786 0.05400098
 0.07396335 0.10614278 0.02798494 0.0914833  0.02203452 0.05350447
 0.08150462 0.03472364 0.0932976  0.08563475 0.09556818 0.09817876
 0.06304395 0.07503274 0.04714863 0.01620013 0.01763884 0.07943611
 0.04862657 0.0587012  0.04898753 0.08289116 0.08570955 0.11513955
 0.10151444 0.03339988 0.02703426 0.07836592 0.01271171 0.03583621
 0.         0.04044903 0.10673654 0.         0.04997367 0.08793759
 0.10142209 0.04174676 0.         0.02855136 0.03135301 0.05563467
 0.04043122 0.         0.09003956 0.01360949 0.03263294 0.
 0.01811534 0.         0.0241012  0.0886186  0.08024359 0.02154859
 0.02295986 0.05922718 0.04092108 0.10381432 0.03487987 0.04217822
 0.06598413 0.10386847 0.17544002 0.08279301 0.07475406 0.
 0.05053966 0.03703902 0.0952447  0.06303437 0.02400666 0.04776416
 0.07967037 0.18607076 0.06292846 0.07263289 0.06735333 0.08358471
 0.01900724 0.04193534 0.0766594  0.04212821 0.03417152 0.03480646
 0.06801605 0.03191142 0.0235887  0.07259634 0.08886677 0.03237415
 0.06189694 0.04429272 0.04014882 0.02162821 0.03112798 0.05289837
 0.05910749 0.08473678 0.0600464  0.0403106  0.07046871 0.
 0.03380554 0.02519081 0.0346956  0.03144206 0.0644887  0.
 0.02393648 0.02424757 0.0309452  0.054354   0.03705284 0.07950625
 0.06498215 0.09762366 0.13457288 0.13117566 0.05584254 0.06421004
 0.08668841 0.0433838  0.05385085 0.09864433 0.         0.02427222
 0.09918717 0.06944177 0.06691801 0.05011346 0.07829971 0.07019115
 0.04510978 0.08065945 0.0307465  0.08200848 0.0215453  0.05961141
 0.0387252  0.04901116 0.07244881 0.02790382 0.02098426 0.08505912
 0.02678624 0.01409253 0.13823734 0.02046176 0.07572052 0.12422686
 0.06764076 0.03316099 0.04978284 0.04338868 0.04647328 0.0477691
 0.08285101 0.04376532 0.05094048 0.09092893 0.03587616 0.04017975
 0.05212035 0.02756385 0.03517362 0.06951391 0.08254084 0.10021848
 0.0796908  0.05732761 0.         0.06475671 0.05886136 0.01793567
 0.0841457  0.02721257 0.06536382 0.07498663 0.08094818 0.05749874
 0.05402243 0.05352843 0.         0.0693135  0.08120074 0.10704009
 1.         0.60492036 0.37006021 0.60532379 0.46860607 0.40105864
 0.06617839 0.01989582 0.05417732 0.04952723 0.06735785 0.12088899
 0.06589336 0.0207635  0.07307152 0.08541443 0.08570888 0.01517818
 0.10647232 0.06913343 0.05282835 0.0465136  0.09690942 0.05690845
 0.12338907 0.05694694 0.09355814 0.04821763 0.04607419 0.01626594
 0.03624235 0.05233369 0.03686728 0.05759353 0.04338919 0.11699863
 0.01978374 0.04270014 0.03833154 0.01686464 0.04530546 0.01222055
 0.08366741 0.06370117 0.05096175 0.0041482  0.027298   0.05988538
 0.03301994 0.05944536 0.03024762 0.07211489 0.05396081 0.05092688
 0.07787846 0.08383098 0.06930111 0.07756275 0.         0.06149282
 0.03175059 0.06998482 0.04373449 0.04031847 0.1135414  0.08093865
 0.0141261  0.08179027 0.         0.0922657  0.07235424 0.05140684
 0.09263632 0.03728116 0.06455973 0.05685772 0.06025766 0.04545006
 0.         0.11860526 0.02551917 0.12529446 0.03876927 0.06109452
 0.07241698 0.0469977  0.05363299 0.09039778 0.10449784 0.06457538
 0.06768944 0.03691227 0.01443222 0.1049394  0.03351914 0.06763077
 0.04477654 0.03348533 0.05863539 0.07299805 0.02936577 0.03187693
 0.05497451 0.08065392 0.07072245 0.08501082 0.01986362 0.11719565
 0.10284329 0.02661461 0.11258818 0.04396007 0.06671169 0.039512
 0.06206377 0.07426749 0.03113502 0.05701361 0.08797834 0.07673146
 0.0681746  0.0223939  0.0748633  0.         0.04975889 0.0464347
 0.04516297 0.01853073 0.05595951 0.08402012 0.04335619 0.
 0.04466058 0.03303126 0.04245941 0.05983822 0.         0.02923637
 0.06510892 0.08304628 0.01429228 0.05242689 0.07530068 0.09181961
 0.09679021 0.08897631 0.0711404  0.09217861 0.02529796 0.09247093
 0.02721553 0.08463225 0.07477865 0.01437994 0.05161078 0.07169148
 0.05150311 0.08538637 0.         0.06698103 0.09224467 0.07189027
 0.06893805 0.02578101 0.         0.06576163 0.05571908 0.05989704
 0.08217191 0.0473936  0.08090109 0.0640823  0.02566608 0.0811105
 0.02537899 0.04666148 0.11738369 0.06090328 0.0409118  0.07198141
 0.07273741 0.         0.07130058 0.04504145 0.03521218 0.
 0.06231222 0.04462691 0.06876917 0.05446891 0.08114117 0.04576379
 0.12323757 0.09657428 0.05942423 0.01735832 0.02670646 0.11929204
 0.03284636 0.02660015 0.0740269  0.08745917 0.         0.03372415
 0.05539301 0.03189296 0.01359299 0.05478036 0.04849505 0.04722438
 0.13286257 0.01905035 0.07167605 0.04158077 0.03287421 0.04668305
 0.08901317 0.08250446 0.02089611 0.04805915 0.03554842 0.02174366
 0.11714585 0.0729268  0.09958602 0.02626887 0.04804581 0.14373907
 0.03451873 0.04159234 0.08565584 0.07200393 0.06367433 0.04052504
 0.03496696 0.02509661 0.06312065 0.02169135 0.12981123 0.07540058
 0.05285501 0.01538159 0.         0.09999685 0.04932539 0.05342147
 0.05151719 0.11855319 0.08037361 0.12805207 0.07493273 0.0926062
 0.13541128 0.06995669 0.02066274 0.04777915 0.05354868 0.04341902
 0.01295837 0.04758697 0.11044181 0.10991714 0.06194962 0.02050212
 0.03542172 0.02634687 0.05400041 0.13003279 0.03834584 0.
 0.         0.08452296 0.10227149 0.07751507 0.03959343 0.07951682
 0.11115382 0.11323579 0.06047257 0.05019393 0.02770971 0.
 0.07977352 0.06484707 0.06433411 0.07000311 0.08838583 0.05570058
 0.06216984 0.03670013 0.10290904 0.09575015 0.06788787 0.03865591
 0.08778509 0.076165   0.12829175 0.0529049  0.02087899 0.11056967
 0.04638367 0.06823821 0.         0.03040706 0.07747373 0.07760777
 0.02533055 0.05568691 0.         0.10779287 0.         0.12070753
 0.01947286 0.05042647 0.07326962 0.0384811  0.07413488 0.09201125
 0.03073801 0.0229703  0.08752584 0.05187675 0.02147444 0.10570236
 0.10929568 0.07393766 0.01836475 0.03469407 0.06244739 0.09158414
 0.02051775 0.05847081 0.06012334 0.05236506 0.1007755  0.11344876
 0.02487466 0.10355258 0.09849578 0.06119322 0.06084241 0.06759181
 0.07946818 0.07730401 0.07869136 0.08510974 0.03244263 0.06720899
 0.0340647  0.02733521 0.04321089 0.05212047 0.07692432 0.0818843
 0.03687527 0.09172953 0.04910969 0.04252905 0.11500717 0.03086979
 0.01756803 0.04193847 0.04350911 0.0270215  0.04131883 0.04672141
 0.05558619 0.15991854 0.0442567  0.06704279 0.03749323 0.
 0.0872054  0.06738158 0.06604817 0.06180793 0.06310453 0.02255489
 0.07739024 0.0255491  0.0482666  0.04585545 0.09227073 0.07978614
 0.06918053 0.14282846 0.03545308 0.10230281 0.06014516 0.05405229
 0.01483033 0.04712252 0.1005254  0.12332427 0.07615669 0.0977385
 0.09078018 0.06849619 0.02174662 0.0506839  0.02503996 0.0732938
 0.03527294 0.02537106 0.04414452 0.01394806 0.05746315 0.01828619
 0.09363818 0.0671967  0.05539621 0.06920601 0.1190751  0.06154799
 0.10900918 0.02524052 0.06349934 0.06471613 0.08580552 0.09107758
 0.08336845 0.09094445 0.03816985 0.0343534  0.06899878 0.
 0.05170872 0.0771758  0.03009617 0.03301795 0.08343162 0.08131317
 0.04306323 0.07253457 0.0251485  0.03743774 0.0102525  0.01259072
 0.10991977 0.0410176  0.03660944 0.04515837 0.05929804 0.11631451
 0.0886632  0.         0.07289252 0.12405063 0.05803743 0.0922848
 0.06556317 0.0328857  0.01771551 0.05833582 0.06443523 0.08446055
 0.04347022]
Index: 219, Similarity Score: 0.6053, Book Title: Harry Potter and the Prisoner of Azkaban (Book 3)
Index: 217, Similarity Score: 0.6049, Book Title: Harry Potter and the Goblet of Fire (Book 4)
Index: 220, Similarity Score: 0.4686, Book Title: Harry Potter and the Sorcerer's Stone (Book 1)
Index: 221, Similarity Score: 0.4011, Book Title: Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))
Index: 218, Similarity Score: 0.3701, Book Title: Harry Potter and the Order of the Phoenix (Book 5)