In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn. tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score

In [2]:
df = pd.read_csv('data_decision_tree_bt.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127282 entries, 0 to 127281
Data columns (total 19 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   TT                       127282 non-null  int64
 1   DoHaiLong                127282 non-null  object
 2   LoaiKhachHang            127282 non-null  object
 3   Tuoi                     127282 non-null  int64
 4   LoaiHinh                 127282 non-null  object
 5   DoTrePhut                126894 non-null  float64
 6   GheNgoi                  127282 non-null  int64
 7   ThucAn                   127282 non-null  int64
 8   GateLocation             127282 non-null  int64
 9   DichVuGuiXe              127282 non-null  int64
 10  BauKhongKhiTranDau       127282 non-null  int64
 11  ChatLuongTranDau         127282 non-null  int64
 12  TraiNghiemDatVeOnline    127282 non-null  int64
 13  ChatLuongCacDichVuDiKem  127282 non-null  int64
 14  DoAnToan                 127282 non-null  int64
 15  ThoiTiet                 127282 non-null  int64
 16  SuSachSe                 127282 non-null  int64
 17  FanDoiNha                127282 non-null  int64
 18  ThietKeLoiDi             127282 non-null  int64
dtypes: float64(1), int64(15), object(3)
memory usage: 18.5+ MB

In [3]:
print(df['DoHaiLong'].unique())
print(df ['LoaiKhachHang'].unique())
print(df['LoaiHinh'].unique())

['Không Hài Lòng' 'Hài Lòng']
['KH Bình Thường' 'KH Trung Thành']
['Đi Cùng Gia Đình/Bạn Bè' 'Đi Cá Nhân']

In [4]:
df.isnull().sum()

TT                           0
DoHaiLong                    0
LoaiKhachHang                0
Tuoi                         0
LoaiHinh                     0
DoTrePhut                  388
GheNgoi                      0
ThucAn                       0
GateLocation                 0
DichVuGuiXe                  0
BauKhongKhiTranDau           0
ChatLuongTranDau             0
TraiNghiemDatVeOnline        0
ChatLuongCacDichVuDiKem      0
DoAnToan                     0
ThoiTiet                     0
SuSachSe                     0
FanDoiNha                    0
ThietKeLoiDi                 0
dtype: int64

In [5]:
df_clean = df.dropna()
df_clean.isnull().sum()

TT                         0
DoHaiLong                  0
LoaiKhachHang              0
Tuoi                       0
LoaiHinh                   0
DoTrePhut                  0
GheNgoi                    0
ThucAn                     0
GateLocation               0
DichVuGuiXe                0
BauKhongKhiTranDau         0
ChatLuongTranDau           0
TraiNghiemDatVeOnline      0
ChatLuongCacDichVuDiKem    0
DoAnToan                   0
ThoiTiet                   0
SuSachSe                   0
FanDoiNha                  0
ThietKeLoiDi               0
dtype: int64

In [17]:
df_clean_encode = pd.get_dummies(df_clean, drop_first=True, dtype=int)
df_clean_encode.columns
df_clean_encode.head()

,TT,Tuoi,DoTrePhut,GheNgoi,ThucAn,GateLocation,DichVuGuiXe,BauKhongKhiTranDau,ChatLuongTranDau,TraiNghiemDatVeOnline,ChatLuongCacDichVuDiKem,DoAnToan,ThoiTiet,SuSachSe,FanDoiNha,ThietKeLoiDi,DoHaiLong_Không Hài Lòng,LoaiKhachHang_KH Trung Thành,LoaiHinh_Đi Cùng Gia Đình/Bạn Bè
0,0,29,15.0,5,5,4,5,2,5,1,5,5,4,5,4,5,1,0,1
1,1,44,0.0,4,5,5,3,1,4,3,4,3,3,2,3,5,1,1,1
2,2,48,0.0,5,2,1,4,2,5,4,5,4,4,4,4,3,0,1,1
3,3,45,0.0,5,5,4,3,2,4,3,5,5,5,5,5,3,0,0,1
4,4,49,0.0,4,4,2,4,1,5,4,5,4,1,4,2,4,1,1,0

In [20]:
# df_clean_encode = df_clean_encode.rename(columns={'DoHaiLong_Không Hai Lòng': 'DoHaiLong',
#                                                          'LoaiKhachHang_KH Trung Thanh': 'LoaiKhachHang',
#                                                          'LoaiHinh_Di Cung Gia Dình/Bạn Bè': 'LoaiHinh'})

df_clean_encode = df_clean_encode.rename(columns={'DoHaiLong_Không Hai Lòng': 'DoHaiLong',
                                                         'LoaiKhachHang_KH Trung Thanh': 'LoaiKhachHang',
                                                         'LoaiHinh_Di Cung Gia Dình/Bạn Bè': 'LoaiHinh'})
df_clean_encode.head()

,TT,Tuoi,DoTrePhut,GheNgoi,ThucAn,GateLocation,DichVuGuiXe,BauKhongKhiTranDau,ChatLuongTranDau,TraiNghiemDatVeOnline,ChatLuongCacDichVuDiKem,DoAnToan,ThoiTiet,SuSachSe,FanDoiNha,ThietKeLoiDi,DoHaiLong_Không Hài Lòng,LoaiKhachHang_KH Trung Thành,LoaiHinh_Đi Cùng Gia Đình/Bạn Bè
0,0,29,15.0,5,5,4,5,2,5,1,5,5,4,5,4,5,1,0,1
1,1,44,0.0,4,5,5,3,1,4,3,4,3,3,2,3,5,1,1,1
2,2,48,0.0,5,2,1,4,2,5,4,5,4,4,4,4,3,0,1,1
3,3,45,0.0,5,5,4,3,2,4,3,5,5,5,5,5,3,0,0,1
4,4,49,0.0,4,4,2,4,1,5,4,5,4,1,4,2,4,1,1,0

In [21]:
y = df_clean_encode['DoHaiLong']
x = df_clean_encode.drop(columns=['DoHaiLong', 'TT'])
print(x.shape(), y.shape())

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
tree = DecisionTreeClassifier(max_depth=4, random_state=42)
tree.fit(x_train, y_train)

tree_pred = tree.predict(x_test)
accuracy = accuracy_score(y_test, tree_pred)
f1_score = f1_score(y_test, tree_pred)
recall = recall_score(y_test, tree_pred)
precision = precision_score(y_test, tree_pred)
print(f'Accuracy: {accuracy}')
print(f'F1 Score: {f1_score}')

print(f'Recall: {recall}')
print(f'Precision: {precision}')

KeyError: 'DoHaiLong'