In [1]:


import numpy as np
import pandas as pd

In [2]:
# Lấy mẫu ngẫu nhiên đơn giản
df_score = pd. DataFrame({'Grade': np. random. randint(50, 100, size=1000) })

df_score.head()

df_sample = df_score.sample(n=50, random_state=42)
df_sample.head()

     Grade
521     87
737     91
740     84
660     55
411     78

In [3]:
# lấy mẫu phân tầng
# Chia dữ liệu thành các cụm (cluster) tự nhiên
# Chọn ngẫu nhiên một số cụm
# Lấy toàn bộ dữ liệu trong các cụm được chọn

import pandas as pd
import numpy as np

sample_size = 50
df_score = pd. DataFrame({'Grade': np. random. randint(50, 100, size=1000) })
df_score['Gender'] = np. random. choice(['Male', 'Female'], size=1000)
# df_sample_grouped = df_score. groupby('Gender'). apply(lambda x: x. sample(n=25, random_state=42))
df_sample_grouped = df_score. groupby('Gender').apply(lambda x: x.sample(n=int(len(x)/len(df_score) * sample_size), random_state=42))
df_sample_grouped.head(50)

C:\Users\Ryan\AppData\Local\Temp\ipykernel_16864\4089672074.py:13: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_sample_grouped = df_score. groupby('Gender').apply(lambda x: x.sample(n=int(len(x)/len(df_score) * sample_size), random_state=42))

            Grade  Gender
Gender
Female 172     77  Female
       625     90  Female
       952     66  Female
       776     82  Female
       345     85  Female
       969     53  Female
       137     75  Female
       373     57  Female
       177     64  Female
       261     81  Female
       160     60  Female
       572     77  Female
       274     66  Female
       150     54  Female
       154     67  Female
       928     61  Female
       504     86  Female
       68      72  Female
       25      64  Female
       117     55  Female
       633     59  Female
       798     93  Female
       620     73  Female
       824     72  Female
       356     62  Female
Male   915     59    Male
       155     93    Male
       881     87    Male
       966     97    Male
       869     59    Male
       638     50    Male
       51      67    Male
       438     60    Male
       989     59    Male
       453     63    Male
       14      75    Male
       233     58    Male
       855     65    Male
       407     91    Male
       745     90    Male
       132     76    Male
       875     79    Male
       878     87    Male
       750     70    Male
       427     97    Male
       146     98    Male
       353     57    Male
       858     68    Male
       101     83    Male

In [ ]:
df_sample_grouped = df_score. groupby('Gender')
df_sample_grouped

In [4]:
#--------------Lấy mẫu 30 giao dịch nhập khẩu bằng phương pháp Simple Random Sampling

data_df = pd.read_csv('USImport.csv', delimiter=';')
random_sample_df = data_df.sample(n=50, random_state=42)
random_sample_df.head()


# Lấy mẫu 30 giao dịch nhập khẩu bằng phương pháp Stratified Sampling (Lấy mẫu phân tầng)

# sẽ như thế nào nếu dữ liệu có hơn 30 groups?

sample_size = 30
# stratified_sample = data_df.groupby('Country of Origin').apply(lambda x: x.sample(n=n_sample) if len(x) >= n_sample else x)

stratified_sample = (
    data_df
    .groupby("Country of Origin", group_keys=False)
    .apply(lambda x: x.sample(
        n=int(len(x) / len(df) * sample_size),
        random_state=42
    ))
)

stratified_sample.head()

# d. Lấy mẫu 30 giao dịch nhập khẩu bằng phương pháp Systematic Sampling (Lấy mẫu hệ thống)

N = len(df)
n = 30
k = N // n
k

start = np.random.randint(0, k)
start

systematic_sample = data_df.iloc[start::k]
systematic_sample.head()

# e. Lấy mẫu 30 giao dịch nhập khẩu bằng phương pháp Cluster Sampling (Lấy mẫu cụm)

# Liệt kê các cluster
clusters = data_df["Country of Origin"].unique()

# Chọn ngẫu nhiên các cluster
selected_clusters = np.random.choice(clusters, size=2, replace=False)

# Lấy toàn bộ dữ liệu trong cluster đã chọn
cluster_sample = data_df[data_df["Country of Origin"].isin(selected_clusters)]
cluster_sample.head()

NameError: name 'df' is not defined

In [ ]:
# Lấy mẫu hệ thống bước nhảy 20 [start:stop:step]
# Sắp xếp dữ liệu theo một thứ tự
# Chọn một điểm bắt đầu ngẫu nhiên
# Sau đó lấy mỗi phần tử thứ k

df_score = pd. DataFrame({'Grade': np.random.randint(50, 100, size=1000) })
n = 50
step = len(df_score)//n
df_sample_step = df_score[::step]
df_sample_step.head()

   Grade
0     90

In [ ]:
# Lấy mẫu cụm
# Chia population thành các cụm (cluster) tự nhiên
# Chọn ngẫu nhiên một số cụm
# Lấy toàn bộ phần tử trong các cụm được chọn

import pandas as pd
import numpy as np

# Tạo dữ liệu giả
np.random.seed(42)

data = {
    "student_id": range(1, 101),
    "class": np.random.choice(["10A", "10B", "10C", "10D", "10E"], 100),
    "score": np.random.randint(50, 100, 100)
}

df = pd.DataFrame(data)
df.head()

# Xác định các cluster
clusters = df["class"].unique()
print(clusters)

# Chọn ngẫu nhiên một số cluster
selected_clusters = np.random.choice(clusters, size=2, replace=False)
print("Selected clusters:", selected_clusters)

# Lấy toàn bộ dữ liệu trong các cluster đã chọn
cluster_sample = df[df["class"].isin(selected_clusters)]
cluster_sample.head()

['10D' '10E' '10C' '10B' '10A']
Selected clusters: ['10C' '10D']

   student_id class  score
0           1   10D     77
2           3   10C     58
6           7   10C     82
7           8   10C     97
8           9   10C     72